language: generic
sudo: required
services:
  - docker

before_install:
  - docker build  -f  Dockerfile.dev  -t andriibalashov/frontend .

script:
  - docker run -e CI=true  andriibalashov/frontend npm run test

